# Target all hosts in the inventory
- hosts: "*"

  # Name of the playbook
  name: Copy Minecraft and Terraria Worlds

  # Make it so that Ansible can "escalate" to root
  # (i.e. run commands using sudo)
  become: true

  # The worlds for which server will be copied
  vars:
    - server: "{{ game }}"

  tasks:
    - name: Print the Game Name
      debug:
        msg: "Copying {{ server }} worlds"

    # ============================================== #
    # MINECRAFT                                      #
    # ============================================== #

    # Added "0755" to the "mode" parameter to make sure that the copied files are editable
    - name: Copy Minecraft Worlds
      copy:
        src: "/opt/ansible/storage/minecraft/worlds"
        dest: "/home/ubuntu/minecraft"
        directory_mode: yes
        mode: "0777"
      when: server == "minecraft"

    # ============================================== #
    # TERRARIA                                       #
    # ============================================== #

    # If you add a "/" at the end of the src path, it will copy the contents of the directory
    # If you don't add a "/" at the end of the src path, it will copy the directory itself
    - name: Copy the Terraria Worlds
      copy:
        src: "/opt/ansible/storage/terraria/worlds/"
        dest: "/home/ubuntu/.local/share/Terraria/Worlds/"
        mode: "0777"
      when: server == "terraria"
