# Target all hosts in the inventory
- hosts: "*"

  # Name of the playbook
  name: Copy Minecraft and Terraria Worlds

  # Make it so that Ansible can "escalate" to root
  # (i.e. run commands using sudo)
  become: true
  tasks:
    # ============================================== #
    # MINECRAFT                                      #
    # ============================================== #

    - name: Copy Minecraft Worlds
      copy:
        src: "/opt/ansible/storage/minecraft/worlds"
        dest: "/home/ubuntu/minecraft"
        directory_mode: yes

    # ============================================== #
    # TERRARIA                                       #
    # ============================================== #

    - name: Copy the Terraria Worlds
      copy:
        src: "/opt/ansible/storage/terraria/worlds"
        dest: "~/.local/share/Terraria/Worlds/"
        directory_mode: yes
