# Target all hosts in the inventory
- hosts: "*"

  # Name of the playbook
  name: Provision the Gaming Server

  # Make it so that Ansible can "escalate" to root
  # (i.e. run commands using sudo)
  become: true
  tasks:
    # ---------------------------------------------- #
    - name: Update Server Packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install Required Server Packages
      apt:
        name:
          - tmux
          - unzip
        state: present

    # ============================================== #
    # MINECRAFT                                      #
    # ============================================== #

    - name: Install Java
      apt:
        name:
          - openjdk-17-jdk
          - openjdk-17-jre
        state: present

    # -------------------------------------------- #
    - name: Create the Root Minecraft Folder
      file:
        path: /home/ubuntu/minecraft
        state: directory
        mode: "0755"

    - name: Download the Latest Minecraft Server .jar
      get_url:
        url: https://piston-data.mojang.com/v1/objects/f69c284232d7c7580bd89a5a4931c3581eae1378/server.jar
        dest: /home/ubuntu/minecraft/server.jar
        mode: "0755"

    # -------------------------------------------- #

    - name: Copy Minecraft Server Properties
      copy:
        src: "/opt/ansible/storage/minecraft/server.properties"
        dest: "/home/ubuntu/minecraft/server.properties"
        mode: "0644"

    # If we don't do this, the server will need to manually accept the EULA
    - name: Copy Minecraft EULA
      copy:
        src: "/opt/ansible/storage/minecraft/eula.txt"
        dest: "/home/ubuntu/minecraft/eula.txt"
        mode: "0644"

    - name: Copy Minecraft Server Icon
      copy:
        src: "/opt/ansible/storage/minecraft/server-icon.png"
        dest: "/home/ubuntu/minecraft/server-icon.png"
        mode: "0644"

    - name: Copy the Minecraft Server Start Script
      copy:
        src: "/opt/ansible/storage/minecraft/start_server.sh"
        dest: "/home/ubuntu/minecraft/start_server.sh"
        mode: "0755"

    # ============================================== #
    # TERRARIA                                       #
    # ============================================== #

    - name: Create the Root Terraria Folder
      file:
        path: /home/ubuntu/terraria
        state: directory
        mode: "0755"

    # -------------------------------------------- #

    - name: Download the Latest Terraria Server .zip
      get_url:
        url: https://terraria.org/api/download/pc-dedicated-server/terraria-server-1447.zip
        dest: /home/ubuntu/terraria/terraria-server.zip
        mode: "0755"

    - name: Unzip the Terraria Server .zip
      unarchive:
        src: /home/ubuntu/terraria/terraria-server.zip
        dest: /home/ubuntu/terraria
        remote_src: yes

    - name: Remove the Terraria Server .zip
      file:
        path: /home/ubuntu/terraria/terraria-server.zip
        state: absent

    - name: Remove the Mac Terraria Server Files
      file:
        path: /home/ubuntu/terraria/1447/Mac
        state: absent

    - name: Remove the Windows Terraria Server Files
      file:
        path: /home/ubuntu/terraria/1447/Windows
        state: absent

    # -------------------------------------------- #

    - name: Add Executable Permissions to the Server Binary
      file:
        path: /home/ubuntu/terraria/1447/Linux/TerrariaServer.bin.x86_64
        mode: "0755"

    - name: Copy the Terraria Starting Script
      copy:
        src: "/opt/ansible/storage/terraria/start_server.sh"
        dest: "/home/ubuntu/terraria/start_server.sh"
        mode: "0755"

    - name: Copy the Terraria Server Config
      copy:
        src: "/opt/ansible/storage/terraria/serverconfig.txt"
        dest: "/home/ubuntu/terraria/1447/Linux/serverconfig.txt"
        mode: "0777"

    # The Terraria server constantly creates a .bak file for your world next to the
    # world file. By default the program won't have permissions to create this file,
    # and will crash trying to backup.
    - name: Add Write Permissions to Allow the Creation of World Backups
      become: true
      command: chmod 777 /home/ubuntu/.local/share/Terraria/Worlds
