# Target all hosts in the inventory
- hosts: "*"

  # Name of the playbook
  name: Provision the Gaming Server

  # Make it so that Ansible can "escalate" to root
  # (i.e. run commands using sudo)
  become: true
  tasks:
    # ---------------------------------------------- #
    - name: Update Server Packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install Required Server Packages
      apt:
        name:
          - tmux
        state: present

    # ============================================== #
    # MINECRAFT                                      #
    # ============================================== #

    # - name: Add Amazon Corretto 16 Public Key
    #   shell: wget -O- https://apt.corretto.aws/corretto.key | sudo apt-key add -

    # - name: Add Amazon Corretto 16 Repository
    #   shell: echo &#039;deb https://apt.corretto.aws stable main&#039; | sudo tee /etc/apt/sources.list.d/corretto.list

    # - name: Update Server Packages
    #   apt:
    #     update_cache: yes

    - name: Install Java
      apt:
        name:
          - default-jre
          - default-jdk
        state: present

    # - name: Install Java package (Ubuntu/Debian)
    #   apt:
    #     name: "openjdk-16-jdk"
    #     state: present
    #     update_cache: yes

    # - name: Add Java Repository
    #   apt_repository:
    #     repo: ppa:linuxuprising/java
    #     state: present

    # - name: Automatically select the Oracle License
    #   shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

    # - name: Install Java
    #   apt:
    #     name: oracle-java17-installer
    #     state: present

    # - name: Append the Linux Uprising PPA to the sources list file
    #   shell: echo "deb http://ppa.launchpad.net/linuxuprising/java/ubuntu focal main" | tee /etc/apt/sources.list.d/linuxuprising-java.list

    # - name: Add the Linux Uprising PPA GPG key
    #   shell: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 73C3DB2A

    # - name: Accept Oracle Java License
    #   debconf:
    #     name: "oracle-java17-installer"
    #     question: "shared/accepted-oracle-license-v1-1"
    #     value: "true"
    #     vtype: "select"

    # - name: Install the Java SDK
    #   apt:
    #     name: "oracle-java17-installer"
    #     state: present

    # -------------------------------------------- #
    - name: Create the Root Minecraft Folder
      file:
        path: /home/ubuntu/minecraft
        state: directory
        mode: "0755"

    - name: Download the Latest Minecraft Server .jar
      get_url:
        url: https://piston-data.mojang.com/v1/objects/f69c284232d7c7580bd89a5a4931c3581eae1378/server.jar
        dest: /home/ubuntu/minecraft/server.jar
        mode: "0755"

    # -------------------------------------------- #

    - name: Copy Minecraft Server Properties
      copy:
        src: "/opt/ansible/storage/minecraft/server.properties"
        dest: "/home/ubuntu/minecraft/server.properties"
        mode: "0644"

    # If we don't do this, the server will need to manually accept the EULA
    - name: Copy Minecraft EULA
      copy:
        src: "/opt/ansible/storage/minecraft/eula.txt"
        dest: "/home/ubuntu/minecraft/eula.txt"
        mode: "0644"

    - name: Copy Minecraft Server Icon
      copy:
        src: "/opt/ansible/storage/minecraft/server-icon.png"
        dest: "/home/ubuntu/minecraft/server-icon.png"
        mode: "0644"

    - name: Copy the Minecraft Server Start Script
      copy:
        src: "/opt/ansible/storage/minecraft/start_server.sh"
        dest: "/home/ubuntu/minecraft/start_server.sh"
        mode: "0755"

    # ============================================== #
    # TERRARIA                                       #
    # ============================================== #

    - name: Create the Root Terraria Folder
      file:
        path: /home/ubuntu/terraria
        state: directory
        mode: "0755"

    - name: Install Required Packages
      apt:
        name:
          - unzip
        state: present

    # -------------------------------------------- #

    - name: Download the Latest Terraria Server .zip
      get_url:
        url: https://terraria.org/api/download/pc-dedicated-server/terraria-server-1447.zip
        dest: /home/ubuntu/terraria/terraria-server.zip
        mode: "0755"

    - name: Unzip the Terraria Server .zip
      unarchive:
        src: /home/ubuntu/terraria/terraria-server.zip
        dest: /home/ubuntu/terraria
        remote_src: yes

    - name: Remove the Terraria Server .zip
      file:
        path: /home/ubuntu/terraria/terraria-server.zip
        state: absent

    # -------------------------------------------- #

    - name: Add Executable Permissions to the Server Binary
      file:
        path: /home/ubuntu/terraria/1447/Linux/TerrariaServer.bin.x86_64
        mode: "0755"

    - name: Copy the Terraria Starting Script
      copy:
        src: "/opt/ansible/storage/terraria/start_server.sh"
        dest: "/home/ubuntu/terraria/start_server.sh"
        mode: "0755"
